apiVersion: v1
kind: Service
metadata: 
  name: web-server-service
  labels: 
    app: web-server-service
spec:
   type: NodePort
   selector:
     app: nginx-webserver
   ports: 
     - protocol: TCP
       port: 80
       targetPort: 80
       nodePort: 30100  
   